name: Issue
description: Please provide as much detail as possible to convey the history of your problem.
title: "[ISSUE]: "
body:
  - type: markdown
    attributes:
      value: Please read our [FAQ](https://github.com/w-okada/voice-changer/blob/master/.github/FAQ.md) before making a bug report!
  - type: input
    id: vc-client-version
    attributes:
      label: Voice Changer Version
      description: Downloaded File Name (.zip)
      placeholder: MMVCServerSIO_xxx_yyyy-zzzz_v.x.x.x.x.zip
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: Operational System
      description: e.g. Windows 10, Ubuntu 20.04, MacOS Venture, MacOS Monterey, etc...
      placeholder: Windows 10
    validations:
      required: true
  - type: input
    id: GPU
    attributes:
      label: GPU
      description: If you have no gpu, please input none.
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checks 
      options:
        - label: I've tried to Clear Settings
        - label: Sample/Default Models are working 
        - label: I've tried to change the Chunk Size
        - label: GUI was successfully launched
        - label: I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
        - label: I've tried to extract to another folder (or re-extract) the .zip file
  - type: input
    id: vc-type
    attributes:
      label: Model Type
      description: MMVC, so-vits-rvc, RVC, DDSP-SVC
      placeholder: RVC
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: Please provide as much reproducible information and logs as possible
  - type: textarea
    id: capture
    attributes:
      label: Application Screenshot
      description: Please provide a screenshot of your application so we can see your settings (you can paste or drag-n-drop)
  - type: textarea
    id: logs-on-terminal
    attributes:
      label: Logs on console
      description: Copy and paste the log on your console here
    validations:
      required: true
