name: Question or Other
description: Do you any question? Use this template
body:
  - type: markdown
    attributes:
      value: We are always working to make our software better, so please be pacient and wait for a response
  - type: textarea
    id: question  
    attributes:
      label: Description
      description: What is your question? (or other non-related to bugs/feature-request)
    validations:
      required: true
