RVC_MODEL_TYPE_NORMAL = 0
RVC_MODEL_TYPE_PITCHLESS = 1
RVC_MODEL_TYPE_WEBUI_256_NORMAL = 2
RVC_MODEL_TYPE_WEBUI_256_PITCHLESS = 3
RVC_MODEL_TYPE_WEBUI_768_NORMAL = 4
RVC_MODEL_TYPE_WEBUI_768_PITCHLESS = 5
RVC_MODEL_TYPE_UNKNOWN = 99
